### ISSUE TITLE
type 'List<dynamic>' is not a subtype of type 'List<DateTime>' of 'result'

### ISSUE THREAD

**Issue by dyalgrupo** [anicdh/date_range_picker#5]
Function showDatePicker crash with this error when you pick a range of Dates and tap on "OK" button.

type 'List<dynamic>' is not a subtype of type 'List<DateTime>' of 'result'.

```
flutter: When the exception was thrown, this was the stack:
flutter: #0      _ModalRoute&TransitionRoute&LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart)
flutter: #1      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:1824:15)
flutter: #2      Navigator.pop (package:flutter/src/widgets/navigator.dart:1183:34)
flutter: #3      _DatePickerDialogState._handleOk (package:date_range_picker/date_range_picker.dart:1114:15)
flutter: #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
flutter: #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
flutter: #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
flutter: #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
flutter: #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
flutter: #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
flutter: #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
flutter: #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
flutter: #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
flutter: #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
flutter: #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
flutter: #17     _invoke1 (dart:ui/hooks.dart:168:13)
flutter: #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
```

**Comment by gaojuanjuan** [comment]
![image](https://user-images.githubusercontent.com/14133759/49207619-6b23a980-f3f0-11e8-9688-ba99e62c086f.png)
Screen adaptation problem
